#This code is intended to mak the final publication quality versions of the figures for this manuscript

# General Data ------------------------------------------------------------
#necessary libraries
library(phangorn)
library(ggplot2)
library(ggrepel)
library(cowplot)

#Read in the species assignment data
species <- read.csv("phylo/JTCoords.csv", header=T)
species$Species <- gsub(pattern = "\\.| " , "", species$Species)
species$Species <- substr(species$Species,1,4)

#make a color blind friendly palette
# consider making this a separate column of species
aruncol <- scale_color_manual(breaks = c("Ahyb", 
                                         "Aapp", 
                                         "Agig", 
                                         "Atec", 
                                         "Unkn"), 
                              values = c("#440154FF", 
                                         "#3B528BFF", 
                                         "#21908CFF", 
                                         "#5DC863FF", 
                                         "#FDE725FF"),
                              labels = c("Hybrid", 
                                         expression(paste(italic("A. appalachiana"))),
                                         expression(paste(italic("A. gigantea"))), 
                                         expression(paste(italic("A. tecta"))), 
                                         "Unknown"))


# MDS Plots ---------------------------------------------------------------
#Read in the previously saved nuclear MDS data as generated by plink
nucmds <- read.table("phylo/nuclear/Nuclear.mds", header=T)
nucmds <- merge(nucmds, species, by.x="FID", by.y="Sample")

NucplotLegend <- ggplot(data = nucmds, aes(x = C1, y = C2, col=Species)) + 
  labs(title="Nuclear Loci", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.text.align = 0) +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = FID)) +
  aruncol

Nucplot <- ggplot(data = nucmds, aes(x = C1, y = C2, col=Species)) + 
  labs(title="Nuclear Loci", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = FID)) +
  aruncol

# Read in the phased WXY, LFY, and plastid distance matrices from SplitsTree4
#consider whether you want to use Hamming distance (like Plink) or a phylogenetic distance
WXYmds <- read.nexus.dist(file="phylo/WXY/WXY.dist.nex")
LFYmds <- read.nexus.dist(file="phylo/LFY/LFY.dist.nex")
Plasmds <- read.nexus.dist(file="phylo/plastid/Plastid_NoMissing.dist.nex")

#Process WXY
WXYfit <- cmdscale(WXYmds, eig=T, k=2) #fit mds
WXYvec <- cbind(rownames(WXYfit$points), WXYfit$points[,1:2])
WXYvec <- merge(WXYvec, species, by.x="V1", by.y="Sample") #merge with species names
WXYvec$V2 <- as.numeric(as.character(WXYvec$V2)) #change col types
WXYvec$V3 <- as.numeric(as.character(WXYvec$V3)) #change col types
WXYvec$Species <- as.factor(WXYvec$Species) #change col types
WXYplot <- ggplot(data = WXYvec, aes(x = V2, y = V3, color=Species)) + 
labs(title="WXY SNPs", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = V1)) +
  aruncol

#Process LFY
LFYfit <- cmdscale(LFYmds, eig=T, k=2) #fit mds
LFYvec <- cbind(rownames(LFYfit$points), LFYfit$points[,1:2])
LFYvec <- merge(LFYvec, species, by.x="V1", by.y="Sample") #merge with species names
LFYvec$V2 <- as.numeric(as.character(LFYvec$V2)) #change col types
LFYvec$V3 <- as.numeric(as.character(LFYvec$V3)) #change col types
LFYvec$Species <- as.factor(LFYvec$Species) #change col types
LFYplot <- ggplot(data = LFYvec, aes(x = V2, y = V3, color=Species)) + 
  labs(title="LFY SNPs", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = V1)) +
  aruncol

#Process Plastid
Plasfit <- cmdscale(Plasmds, eig=T, k=2) #fit mds
Plasvec <- cbind(rownames(Plasfit$points), Plasfit$points[,1:2])
Plasvec <- merge(Plasvec, species, by.x="V1", by.y="Sample") #merge with species names
Plasvec$V2 <- as.numeric(as.character(Plasvec$V2)) #change col types
Plasvec$V3 <- as.numeric(as.character(Plasvec$V3)) #change col types
Plasvec$Species <- as.factor(Plasvec$Species) #change col types
PlasPlot <- ggplot(data = Plasvec, aes(x = V2, y = V3, color=Species)) + 
  labs(title="Plastid SNPs", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = V1)) +
  aruncol

#Make Final Plot
legend <- get_legend(NucplotLegend + 
                       theme(legend.position = "bottom",
                             legend.justification="center"))
right_side <- plot_grid(PlasPlot, WXYplot,nrow=2, labels=c("B", "C"))
main <- plot_grid(Nucplot, right_side, ncol=2, labels=c("A"))
plot_grid(main, legend, nrow=2, rel_heights = c(1,0.1))



title <- ggdraw() + draw_label("Conditions for site 05430175", fontface='bold')
bottom_row <- plot_grid(nutrient_boxplot, tss_flow_plot, ncol = 2, labels = "AUTO")
plot_grid(title, bottom_row, flow_timeseries, nrow = 3, labels = c("", "", "C"),
          rel_heights = c(0.2, 1, 1))
