#This code is intended to mak the final publication quality versions of the figures for this manuscript

# General Data ------------------------------------------------------------
#necessary libraries
library(phangorn)
library(ggplot2)
library(ggrepel)
library(cowplot)
theme_set(theme_cowplot())

#Read in the species assignment data
species <- read.csv("phylo/JTCoords.csv", header=T)
species$Species <- gsub(pattern = "\\.| " , "", species$Species)
species$Species <- substr(species$Species,1,4)
species$Species <- factor(species$Species, levels=c("Aapp", "Agig", "Atec", "Ahyb", "Unkn"))

# make a color blind friendly palette
aruncol <- scale_color_manual(breaks = levels(species$Species),
                              values = c("#000000FF", 
                                         "#2A788EFF",
                                         "#FFCC00FF", 
                                         "#000000FF", 
                                         "#7AD151FF"),
                              labels = c(expression(paste(italic("A. appalachiana"))),
                                         expression(paste(italic("A. gigantea"))), 
                                         expression(paste(italic("A. tecta"))), 
                                         "Hybrid",
                                         "Hull Road"))

# shape hybrid sampels differently
arunshape <- scale_shape_manual(breaks = levels(species$Species),
                                values = c(16, 16, 16, 4, 16),
                                labels = c(expression(paste(italic("A. appalachiana"))),
                                           expression(paste(italic("A. gigantea"))), 
                                           expression(paste(italic("A. tecta"))), 
                                           "Hybrid",
                                           "Hull Road"))


# MDS Plots ---------------------------------------------------------------
#Read in the previously saved nuclear MDS data as generated by plink
nucmds <- read.table("phylo/nuclear/Nuclear.mds", header=T, stringsAsFactors = F)
nucmds <- merge(nucmds, species, by.x="FID", by.y="Sample")

NucplotLegend <- ggplot(data = nucmds, aes(x = C1, y = C2, col=Species, shape=Species)) + 
  labs(title="Nuclear Loci \n(Ambiguous)", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.text.align = 0) +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = FID)) +
  aruncol +
  arunshape

Nucplot <- NucplotLegend + 
  theme(legend.position = "none")

# Read in the phased WXY, LFY, and plastid distance matrices from SplitsTree4
#consider whether you want to use Hamming distance (like Plink) or a phylogenetic distance
WXYmds <- read.nexus.dist(file="phylo/WXY/WXY.dist.nex")
LFYmds <- read.nexus.dist(file="phylo/LFY/LFY.dist.nex")
Plasmds <- read.nexus.dist(file="phylo/plastid/Plastid_NoMissing.dist.nex")

#Process WXY
WXYfit <- cmdscale(WXYmds, eig=T, k=2) #fit mds
WXYvec <- cbind(rownames(WXYfit$points), WXYfit$points[,1:2])
WXYvec <- merge(WXYvec, species, by.x="V1", by.y="Sample") #merge with species names
WXYvec$V2 <- as.numeric(as.character(WXYvec$V2)) #change col types
WXYvec$V3 <- as.numeric(as.character(WXYvec$V3)) #change col types
WXYplot <- ggplot(data =WXYvec, aes(x = V2, y = V3, color=Species, shape=Species)) + 
labs(title="WXY SNPs \n(Phased)", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(data=subset(WXYvec, Species == "Unkn"), aes(label = V1)) +
  aruncol + 
  arunshape

#Process LFY
LFYfit <- cmdscale(LFYmds, eig=T, k=2) #fit mds
LFYvec <- cbind(rownames(LFYfit$points), LFYfit$points[,1:2])
LFYvec <- merge(LFYvec, species, by.x="V1", by.y="Sample") #merge with species names
LFYvec$V2 <- as.numeric(as.character(LFYvec$V2)) #change col types
LFYvec$V3 <- as.numeric(as.character(LFYvec$V3)) #change col types
LFYplot <- ggplot(data = LFYvec, aes(x = V2, y = V3, color=Species, shape=Species)) + 
  labs(title="LFY SNPs \n(Phased)", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = V1)) +
  aruncol

#Process Plastid
Plasfit <- cmdscale(Plasmds, eig=T, k=2) #fit mds
Plasvec <- cbind(rownames(Plasfit$points), Plasfit$points[,1:2])
Plasvec <- merge(Plasvec, species, by.x="V1", by.y="Sample") #merge with species names
Plasvec$V2 <- as.numeric(as.character(Plasvec$V2)) #change col types
Plasvec$V3 <- as.numeric(as.character(Plasvec$V3)) #change col types
PlasPlot <- ggplot(data = Plasvec, aes(x = V2, y = V3, color=Species, shape=Species)) + 
  labs(title="Plastid SNPs \n(Phased)", x="Dimension 1", y="Dimension 2") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none") +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = V1)) +
  aruncol +
  arunshape

#Make Final Plot
legend <- get_legend(NucplotLegend + 
                       theme(legend.position = "bottom",
                             legend.justification="center",
                             legend.title = element_blank()))
right_side <- plot_grid(PlasPlot, WXYplot,nrow=2, labels=c("B", "C"))
main <- plot_grid(Nucplot, right_side, ncol=2, labels=c("A"))
plot_grid(main, legend, nrow=2, rel_heights = c(1,0.1))

ggsave2(filename = "Figure 1.pdf", height = 6,width=9)


# SplitsTrees -------------------------------------------------------------
# Make color-coded splitstree plots of the datasets
library(phangorn)
SplitsPlas <- read.nexus.networx("phylo/splitstree/Plastid_NoMissing.splits.nex")

## I need to find a way to create a vector of species names/colors for plotting that is indexed to the tip labels of each network.


#Scratch for plot
# Write a plot with colored names showing phylo placement.
pdf(file = "concatenated/ConcatenatedSNPSplits.pdf", width=7, height=6)
par(mar = c(0,0,2,0))
plot(splits, "2D",
     tip.col = species2,
     edge.width = 1.5, 
     cex = 1, 
     font = 3)
title(main = "Nuclear and Plastid SNP SplitsTree")
legend("topleft",legend=c("Hybrid", "A. appalachiana", "A. gigantea", "A. tecta", "Unknown"),col=colmap, pch=16, bty="n")
dev.off()

#plot nuclear only snps splitstree
pdf(file = "nuclear/NuclearSNPSplits.pdf", width = 7, height = 5)
par(mar = c(0,0,1,0))
plot(splits, "2D",
     tip.col = species2,
     edge.width = 1.5, 
     cex = 1, 
     font = 3)
title(main = "Nuclear SNP SplitsTree")
legend("bottomleft",legend=c("Hybrid", "A. appalachiana", "A. gigantea", "A. tecta", "Unknown"),col=colmap, pch=16, bty="n")
dev.off()

